## code to prepare get_data` dataset goes here

library(magrittr)

pars <- read_config()
googleCloudStorageR::gcs_auth(json_file = "auth/gcp-sa-peskas_ingestion-key.json")


#' Authenticate to a storage cloud provider
#'
#' Usually used internally by other functions
#'
#' @param provider cloud provider to use, either "gcs" or "aws"
#' @param options named list with cloud provider options, see details
#'
#' @details
#'
#' ### Google Cloud Services
#'
#' For Google Cloud Services ("gcs") options must be a list with the field
#' `service_account_key` with the contents of the authentication json file you
#' have downloaded from your Google Project.
#'
#' This function uses [googleCloudStorageR::gcs_auth] under the hood to
#' authenticate.
#'
#' @examples
#'
#' # Google Cloud Services
#' \dontrun{
#' authentication_details <- readLines("location_of_json_file.json")
#' cloud_storage_authenticate(
#'   provider = "gcs",
#'   options = list(
#'     service_account_key = authentication_details,
#'     bucket = "my-bucket"
#'   )
#' )
#' }
cloud_storage_authenticate <- function(provider, options) {
  if ("gcs" %in% provider) {
    # Only need to authenticate if there is no token for downstream requests
    if (isFALSE(googleAuthR::gar_has_token())) {
      service_account_key <- options$service_account_key
      temp_auth_file <- tempfile(fileext = "json")
      writeLines(service_account_key, temp_auth_file)
      googleCloudStorageR::gcs_auth(json_file = temp_auth_file)
    }
  }
}

#' Get the full name of a versioned cloud object
#'
#' Obtain the full name (e.g.
#' `timor-landings-v2_metadata__20210326084600_54617b3__.json`) of a cloud
#' storage object. If there are more than one object matching the prefix,
#' version, and extension, a vector with all the names is returned.
#'
#' @param prefix string indicating the prefix of the object
#' @param version either "latest" or the specific version string generated by
#'   [add_version] when the file was uploaded to the cloud provider
#' @param extension extension of the desired file. Use an empty string "" to
#'   return all extensions founds
#' @param provider
#' @param exact_match logical indicating whether the prefix should be matched
#'   exactly
#' @param options
#' @inheritParams upload_cloud_file
#'
#'
#' @details
#'
#' ### Google Cloud Services
#'
#' For Google Cloud Services ("gcs") options must be a list with two fields:
#' `bucket` with the bucketname (character) you are uploading to, and
#' `service_account_key` with the contents of the authentication json file you
#' have downloaded from your Google Project (if [cloud_storage_authenticate] has
#' not been called before).
#'
#' This function uses [googleCloudStorageR::gcs_upload] under the hood to upload
#' the file.
#'
#' @return A string vector with the object names in the cloud storage that match
#'   the prefix, the version, and the extension indicated in the parameters
#'
#' @examples
#'
#' #' # Google Cloud Services
#' \dontrun{
#' authentication_details <- readLines("location_of_json_file.json")
#' # obtain the latest version of all files corresponding to timor-landings-v2
#' cloud_object_name(
#'   prefix = "timor-landings-v2",
#'   version = "latest",
#'   provider = "gcs",
#'   options = list(
#'     service_account_key = authentication_details,
#'     bucket = "my-bucket"
#'   )
#' )
#'
#' # obtain a specific version of the structured data from timor-landings-v2
#' cloud_object_name(
#'   prefix = "timor-landings-v2_raw",
#'   version = "20210326084600_54617b",
#'   extension = "csv",
#'   provider = "gcs",
#'   options = list(
#'     service_account_key = authentication_details,
#'     bucket = "my-bucket"
#'   )
#' )
#' }
#'
cloud_object_name <- function(prefix, version = "latest", extension = "",
                              provider, exact_match = FALSE, options) {
  cloud_storage_authenticate(provider, options)

  if ("gcs" %in% provider) {
    gcs_files <- googleCloudStorageR::gcs_list_objects(
      bucket = options$bucket,
      prefix = prefix
    )

    if (nrow(gcs_files) == 0) {
      return(character(0))
    }

    gcs_files_formatted <- gcs_files %>%
      tidyr::separate(
        col = .data$name,
        into = c("base_name", "version", "ext"),
        # Version is separated with the "__" string
        sep = "__",
        remove = FALSE
      ) %>%
      dplyr::filter(stringr::str_detect(.data$ext, paste0(extension, "$"))) %>%
      dplyr::group_by(.data$base_name, .data$ext)

    if (isTRUE(exact_match)) {
      selected_rows <- gcs_files_formatted %>%
        dplyr::filter(.data$base_name == prefix)
    } else {
      selected_rows <- gcs_files_formatted
    }

    if (version == "latest") {
      selected_rows <- selected_rows %>%
        dplyr::filter(max(.data$updated) == .data$updated)
    } else {
      selected_rows <- selected_rows %>%
        dplyr::filter(.data$version == version)
    }

    selected_rows$name
  }
}


#' Download an object from a cloud storage bucket to a local file
#'
#' Download object from the cloud storage to a local file
#'
#' @param name the name of the object in the storage bucket.
#' @param provider
#' @param options
#' @param file a file-path (character) where the object will be saved. Default
#'   is the object name.
#' @inheritParams upload_cloud_file
#'
#'
#' @return the file path
#'
#' @examples
#'
#' # Google Cloud Services
#' \dontrun{
#' authentication_details <- readLines("location_of_json_file.json")
#' download_cloud_file(
#'   name = "timor-landings-v2_metadata__20210326084600_54617b3__.json",
#'   provider = "gcs",
#'   options = list(
#'     service_account_key = authentication_details,
#'     bucket = "my-bucket"
#'   )
#' )
#' }
download_cloud_file <- function(name, provider, options, file = name) {
  cloud_storage_authenticate(provider, options)

  if ("gcs" %in% provider) {
    purrr::map2(
      name, file,
      ~ googleCloudStorageR::gcs_get_object(
        object_name = .x,
        bucket = options$bucket,
        saveToDisk = .y,
        overwrite = ifelse(is.null(options$overwrite), TRUE, options$overwrite)
      )
    )
  }

  file
}

get_file <- function(prefix) {
  if (prefix == "metadata-tables_preprocessed") {
    options <- pars$storage_meta$google$options
  } else {
    options <- pars$storage$google$options
  }

  filename <- cloud_object_name(
    prefix = prefix,
    provider = pars$storage$google$key,
    extension = "rds",
    options = options,
    exact_match = TRUE
  )
  download_cloud_file(
    name = filename,
    provider = pars$storage$google$key,
    options = options
  )

  x <- readRDS(filename)
  file.remove(filename)
  date_modified <- strptime(strsplit(filename, "_")[[1]][4], format = "%Y%m%d%H%M")

  attr(x, "data_last_updated") <- date_modified
  x
}

get_merged_trips <- function(pars, ...) {
  cloud_object_name(
    prefix = paste0(pars$merged_trips$prefix),
    provider = pars$storage_meta$google$key,
    options = pars$storage_meta$google$options,
    ...
  ) %>%
    download_cloud_file(
      provider = pars$storage_meta$google$key,
      options = pars$storage_meta$google$options
    ) %>%
    readr::read_rds()
}

#' Preprocess and store report data
#'
#' The function load catches and trips data, preprocess and combine them to
#' return a dataframe ready to be analysed and stored in the folder `data`.
#'
#' @param ... Any additional arguments
#'
#' @return A dataframe `report_data` in `data` folder
#' @export
#'
store_data <- function(...) {
  # Download file
  trips <- get_file("timor_trips")
  catch <- get_file("timor_catch")
  metadata <- get_file("metadata-tables_preprocessed")

  catch_clean <-
    catch %>%
    dplyr::group_by(.data$trip_id, .data$catch_taxon) %>%
    dplyr::select(-c(.data$length_type, .data$Selenium_mu:.data$Vitamin_A_mu)) %>%
    dplyr::ungroup()

  report_data <-
    catch_clean %>%
    dplyr::left_join(trips, by = "trip_id") %>%
    dplyr::mutate(n_fishers = .data$fisher_number_man + .data$fisher_number_woman + .data$fisher_number_child) %>%
    dplyr::select(
      .data$trip_id, .data$landing_date, .data$landing_survey_trip_duration, .data$reporting_region,
      .data$landing_station, .data$habitat, .data$gear_type, .data$n_fishers, .data$landing_value,
      .data$catch_taxon, .data$catch_purpose, .data$length, .data$individuals, .data$weight
    ) %>%
    dplyr::filter(.data$landing_date < "2021-12-31") %>%
    dplyr::mutate(area = dplyr::case_when(
      .data$reporting_region %in% c("Bobonaro", "Liquiça", "Dili", "Baucau", "Oecusse") |
        .data$landing_station %in% c(
          "Com", "Tutuala", "Ililai",
          "Sentru/Liarafa/Sika/Rau Moko", "Comando"
        ) ~ "North Coast",
      .data$reporting_region == "Atauro" ~ "Atauro island",
      is.na(.data$reporting_region) | is.na(.data$reporting_region) |
        is.na(.data$reporting_region) & is.na(.data$reporting_region) ~ NA_character_,
      TRUE ~ "South Coast"
    )) %>%
    dplyr::mutate(fish_group = dplyr::case_when(
      catch_taxon %in% c("COZ") ~ "Molluscs",
      catch_taxon %in% c("PEZ") ~ "Shrimps",
      catch_taxon %in% c("MZZ") ~ "Unknown",
      catch_taxon %in% c("SLV", "CRA") ~ "Crustaceans",
      catch_taxon %in% c("OCZ", "IAX") ~ "Cephalopods",
      catch_taxon %in% c("SKH", "SRX") ~ "Sharks and rays",
      catch_taxon %in% c("SNA", "GPX", "PWT", "SUR", "GRX", "MUI", "BGX") ~ "Large demersals",
      catch_taxon %in% c("CGX", "TUN", "BEN", "LWX", "BAR", "SFA", "CBA", "DOX", "ECN", "DOS") ~ "Large pelagics",
      catch_taxon %in% c("YDX", "SPI", "EMP", "SUR", "TRI", "MOJ", "WRA", "MOO", "BWH", "LGE", "MOB", "MHL", "GOX", "THO", "IHX", "APO", "IHX", "PUX", "DRZ") ~ "Small demersals",
      catch_taxon %in% c("RAX", "SDX", "CJX", "CLP", "GZP", "FLY", "KYX", "CLP", "MUL", "DSF", "MIL", "THF") ~ "Small pelagics",
      TRUE ~ NA_character_
    )) %>%
    dplyr::mutate(
      period = dplyr::case_when(
        .data$landing_date < "2020-03-28" ~ "pre-pandemic", TRUE ~ "pandemic"
      ),
      area = as.factor(.data$area),
      fish_group = as.factor(.data$fish_group),
      gear_type = as.factor(.data$gear_type)
    ) %>%
    dplyr::select(
      .data$trip_id:.data$landing_survey_trip_duration, .data$area,
      .data$reporting_region:.data$landing_value,
      .data$fish_group, tidyselect::everything()
    ) %>%
    dplyr::filter(!is.na(.data$fish_group))

  report_data <-
    metadata$catch_types %>%
    dplyr::rename(catch_taxon = interagency_code) %>%
    dplyr::select(catch_taxon, catch_name_en) %>%
    dplyr::rename(catch_name = catch_name_en) %>%
    dplyr::left_join(report_data, by = "catch_taxon") %>%
    dplyr::mutate(catch_name = dplyr::case_when(
      .data$catch_name == "Jacks/Trevally/Other Scad" ~ "Jacks/Trevally",
      .data$catch_name == "Tuna/Bonito/Other Mackerel" ~ "Tuna/Bonito",
      .data$catch_name == "hort bodied mackerel" ~ "Short mackerel",
      TRUE ~ .data$catch_name
    )) %>%
    dplyr::select(
      .data$trip_id:.data$landing_survey_trip_duration, .data$area,
      .data$reporting_region:.data$landing_value,
      .data$fish_group, .data$catch_name, tidyselect::everything()
    ) %>%
    dplyr::filter(!is.na(.data$area) |
      !is.na(.data$area))

  usethis::use_data(report_data, overwrite = TRUE)
}
store_data()

get_trips_week <- function(pars, trips_data = NULL) {
  merged_trips <- get_merged_trips(pars)
  file.remove(list.files(pattern = pars$merged_trips$prefix, full.names = TRUE))

  tidy_trips <-
    merged_trips %>%
    dplyr::select(
      landing_id, tracker_trip_id, landing_date,
      tracker_imei, reporting_region, landing_station
    ) %>%
    dplyr::filter(.data$landing_date < "2021-12-31") %>%
    dplyr::mutate(
      landing_date = as.Date(landing_date),
      month_period = lubridate::floor_date(landing_date, unit = "month"),
      week = lubridate::week(landing_date),
      area = dplyr::case_when(
        .data$reporting_region %in% c("Bobonaro", "Liquiça", "Dili", "Baucau", "Oecusse") |
          .data$landing_station %in% c(
            "Com", "Tutuala", "Ililai",
            "Sentru/Liarafa/Sika/Rau Moko", "Comando"
          ) ~ "North Coast",
        .data$reporting_region == "Atauro" ~ "Atauro island",
        is.na(.data$reporting_region) | is.na(.data$reporting_region) |
          is.na(.data$reporting_region) & is.na(.data$reporting_region) ~ NA_character_,
        TRUE ~ "South Coast"
      )
    ) %>%
    dplyr::select(
      area, landing_id, tracker_trip_id,
      month_period, week, tracker_imei
    ) %>%
    dplyr::filter(!is.na(area))

  trips_tracked <-
    tidy_trips %>%
    dplyr::filter(!is.na(tracker_trip_id)) %>%
    dplyr::group_by(area, month_period, week) %>%
    dplyr::summarise(trips_tracked_week = dplyr::n())

  boats_tracked <-
    tidy_trips %>%
    dplyr::mutate(tracker_trip_id = dplyr::case_when(!is.na(tracker_trip_id) ~ "yes", TRUE ~ "no")) %>%
    dplyr::rename(tracked = tracker_trip_id) %>%
    dplyr::group_by(area, month_period, week, tracked) %>%
    dplyr::summarise(boats_n = dplyr::n()) %>%
    dplyr::mutate(
      total_trips = sum(boats_n),
      tracked_boats_perc = boats_n / total_trips * 100
    ) %>%
    dplyr::filter(tracked == "yes")

  trips_per_week <-
    dplyr::left_join(trips_tracked, boats_tracked) %>%
    dplyr::select(area, month_period, trips_tracked_week, tracked_boats_perc) %>%
    dplyr::mutate(trips_week = (trips_tracked_week / tracked_boats_perc) * 100) %>%
    dplyr::group_by(area, month_period) %>%
    dplyr::summarise(
      sum = sum(trips_week, na.rm = TRUE),
      mean = mean(trips_week, na.rm = TRUE),
      sd = sd(trips_week, na.rm = TRUE),
      n = dplyr::n(),
      sem = (sd / sqrt(n - 1)),
      CI_lower = (mean + qt((1 - 0.90) / 2, df = n - 1) * sem),
      CI_upper = (mean - qt((1 - 0.90) / 2, df = n - 1) * sem),
      CI_lower = ifelse(CI_lower < 0, 0, CI_lower)
    )
  trips_per_week
}

trips_per_week <- get_trips_week(pars, trips_data = merged_trips)
usethis::use_data(trips_per_week, overwrite = TRUE)

devtools::document()
