---
title: "Modelling scenarios for nutrient-sensitive fisheries management"
date: "Last compiled on `r Sys.time()`"
mainfont: Montserrat
geometry: "left=3cm,right=3cm,top=2cm,bottom=2cm"
output:
  bookdown::pdf_book:
    latex_engine: lualatex
    toc: yes
    toc_depth: 2
    number_sections: true
  bookdown::word_document2:
    number_sections: true
    toc: true
  bookdown::html_document2:
    number_sections: true
    toc: true
header-includes: 
  - \usepackage{float} 
  - \floatplacement{figure}{H}
  - \usepackage{leading}
  - \leading{16pt}
  - \definecolor{myblue}{RGB}{68,117,151}
  - \let\counterwithout\relax
  - \let\counterwithin\relax
  - \usepackage{chngcntr}
  - \usepackage{caption}
  - \captionsetup[figure]{font=footnotesize}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE)
```

```{r, include=FALSE}
# libraries
library(magrittr)
library(ggplot2)
library(tidytext)
library(timetk)
library(wesanderson)

#load data
report_data <- timor.report::report_data

setwd("../..")
pars <- timor.report::read_config()

label_date <- function(x) {
  format(x, "%b") %>%
    stringr::str_replace("Jan", paste0("Jan\n", format(x, "%Y")))
}

```


# Data summary

## Regions' temporal coverage

(ref:missing) Temporal coverage of each municipality on the aggregated daily scale.

```{r missings, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=6, fig.cap='(ref:missing)'}

report_data %>% 
  ggplot(aes(landing_date,weight))+
  theme_minimal(12)+
  geom_line()
```

